const teams = [
  { id: 244, name: "Argentina", coach: "Lionel Scaloni" },
  { id: 27, name: "Belgium", coach: "Roberto Martínez" },
  { id: 247, name: "Brazil", coach: "Tite" },
  { id: 1428, name: "Cameroon", coach: "Rigobert Song" },
  { id: 225, name: "Canada", coach: "John Herdman" },
  { id: 30, name: "Croatia", coach: "Zlatko Dalić" },
  { id: 25, name: "Denmark", coach: "Kasper Hjulmand" },
  { id: 1077, name: "Ecuador", coach: "Gustavo Alfaro" },
  { id: 29, name: "England", coach: "Gareth Southgate" },
  { id: 35, name: "France", coach: "Didier Deschamps" },
  { id: 36, name: "Germany", coach: "Hansi Flick" },
  { id: 1429, name: "Ghana", coach: "Franky Vercauteren" },
  { id: 242, name: "Iran", coach: "Dragan Skočić" },
  { id: 251, name: "Japan", coach: "Hajime Moriyasu" },
  { id: 234, name: "Mexico", coach: "Gerardo Martino" },
  { id: 241, name: "Morocco", coach: "Vahid Halilhodžić" },
  { id: 31, name: "Netherlands", coach: "Louis van Gaal" },
  { id: 40, name: "Poland", coach: "Czesław Michniewicz" },
  { id: 39, name: "Portugal", coach: "Fernando Santos" },
  { id: 1078, name: "Qatar", coach: "Félix Sánchez" },
  { id: 248, name: "Republic of Korea", coach: "Paulo Bento" },
  { id: 238, name: "Saudi Arabia", coach: "Hervé Renard" },
  { id: 252, name: "Senegal", coach: "Aliou Cissé" },
  { id: 160, name: "Serbia", coach: "Dragan Stojković" },
  { id: 33, name: "Spain", coach: "Luis Enrique" },
  { id: 24, name: "Switzerland", coach: "Murat Yakin" },
  { id: 249, name: "Tunisia", coach: "Jalel Kadri" },
  { id: 240, name: "Uruguay", coach: "Diego Alonso" },
  { id: 232, name: "USA", coach: "Gregg Berhalter" },
];

export default teams;
